name: tictactoe_server
version: 1.0.0
description: Multiplayer Tic-Tac-Toe game server in Dart

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  sqlite3: ^2.4.6
  dart_jsonwebtoken: ^2.14.1
  mailer: ^6.1.2
  uuid: ^4.4.2
  crypto: ^3.0.5
  encrypt: ^5.0.3
  args: ^2.5.0
  dotenv: ^4.2.0
